# Generated by Django 4.2.6 on 2023-10-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='des',
            field=models.ImageField(upload_to=''),
        ),
    ]
